### ISSUE TITLE
Rajout des commande du step: Redeploy the app (with cloudant)

### ISSUE THREAD

**Issue by jmoliva** [lionelmace/iks-lab#11]
la tete du yaml après modif:
```yaml
# Application to deploy
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mytodos
spec:
  replicas: 2 # tells deployment to run 2 pods matching the template
  selector:
    matchLabels:
      app: mytodos
  template:   # create pods using pod definition in this template
    metadata:
      labels:
        app: mytodos
        tier: frontend
    spec:
      containers:
      - name: mytodos
        image: registry.eu-de.bluemix.net/lab-registry/todo-jmo:1.0
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 250m     # 250 millicores = 1/4 core
            memory: 128Mi # 128 MB
          limits:
            cpu: 500m
            memory: 384Mi
        envFrom:
          - secretRef:
              name: database-credentials
```

la commande pour mettre à jour la config:
`kubectl apply -f deploy-app.yaml`
